-- AlterTable
ALTER TABLE "Cohort" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP;
